:linkattrs:

= Spring Boot Config

This example shows how to bootstrap kubernetes https://kubernetes.io/docs/tasks/configure-pod-container/configmap/[ConfigMap] to the Spring Boot properties

== Build and Deploying

[code,sh]
----
./mvn clean fabric8:deploy

oc get pods -w <1>
----

<1> Ensure the application is deployed and available to run

== Accessing application

Find the route of the applicaiton using the command `oc get route spring-boot-greeter`, and try the following

[code,sh]
----
curl $(oc get route spring-boot-greeter | awk 'END{print $2}')/greet/<name>
----

This should display the greeting with prefix configured for property `greeter.prefix` link:./src/main/fabric8/cm.yaml[cm.yaml]


=== Applying changes

Edit the config map via `oc edit configmap spring-boot-greeter` and change the `greeter.prefix` to what you want
and delete the existing pod, once the new pod is refreshed and you access the application as described in previous
section then you should see value you updated.


[NOTE]
====
Ideally the delete pod is not required, as the spring-cloud-kubernetes library takes care of it, but with the version of
spring cloud library it does not seem to work.
====